### ISSUE TITLE
Sphinx doc issues

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#501]
A list of issues in the sphinx docs that need fixing. This is so I don't forget:

- [X] simple user model example has cut-off text: ``Visually comparing the model and data values highlights how poor this fit is (the data plot needs re-generating because ::``. See #528
- [X] The astropy glossary entry says ``A community Python library for Astronomy: <http://www.astropy.org/>_.`` There should be a link but not the ``<..>_`` part. See #528
- [X] the "edit on GitHub" links do not work 1: https://github.com/sherpa/sherpa/blob/master/home/docs/checkouts/readthedocs.org/user_builds/sherpa/checkouts/latest/docs/conf.py/index.rst  - this seems to have been https://github.com/rtfd/readthedocs.org/issues/4671 and I've just checked on a doc build today and it now works 
- [X] the "edit on GitHub" links do not work 2: select the edit on https://sherpa.readthedocs.io/en/latest/ui/api/sherpa.ui.fit.html and get taken to https://github.com/sherpa/sherpa/blob/master/docs/ui/api/sherpa.ui.fit.rst (it was a different url before RTFDs 4671 fix landed). This makes sense because this is an auto-generated file. Need to investigate how this is handled (or if we should just hide the edit links on these pages). **TODO** look at https://github.com/rtfd/readthedocs-sphinx-ext/issues/28 - I have also had **some** success using `sphinx_astropy.edit_on_github`. See #528

**Comment by hamogu** [comment]
Seems that you can close this since all points have been addressed?

**Comment by DougBurke** [comment]
@hamogu I'm not sure the "edit on github" issues are truly resolved, but you're probably right that this can be closed.

**Comment by anetasie** [comment]
@DougBurke Can we close this issue?

**Comment by DougBurke** [comment]
yeah. I'm not convinced all the subltleties of edit-on-github are fixed, but I think we should open a new ticket if we ever see aproblem. The number of edits we are getting from the community is rather small, so it's not  high on my priority list at the moment!
